Automattic/lando-cli

lib/app.js, lib/bootstrap.js, lib/daemon.js, lib/lando.js, lib/scan.js, plugins/lando-core/app.js, plugins/lando-core/index.js, plugins/lando-proxy/index.js, plugins/lando-services/lib/utils.js, plugins/lando-tooling/lib/utils.js
Docker compose v2 switched from using `_` to `-` as a seperator in container ids. 
In lando there are several places where `_` was hardcoded which made it incompatible with docker-compose v2. 
This change seems to address most of those. I am yet to fully test this within our dev-env but that will be easier with this merged.
=> Docker compose v2

lib/daemon.js
On `darwin 21.5.0` getVersions fails to find docker-compose version.
I opened an issue on upstream - https://github.com/lando/cli/issues/153
For now we just fallback to v1
=> Fallback to compose v1

plugins/lando-proxy/services/proxy/builder.js
In https://github.com/Automattic/vip-container-images/pull/280 we bumped `traefik` from 2.7 which has reached its EOL. This change switches to the new image.
=> Bump proxy version from 2.7 to 2.8

plugins/lando-core/app.js, plugins/lando-core/index.js
When `lando.config.home` is empty, Lando nevertheless tries to create (and later scan) the `.ssh` directory. When `home` is empty, `.ssh` is created in the current directory.
This PR suppresses all access to `.ssh` if `lando.config.home` is empty.
=> fix: Do not touch .ssh if config.home is empty

lib/config.js
```
Error: Cannot read properties of null (reading 'pluginDirs')
@automattic/vip:bin:dev-environment TypeError: Cannot read properties of null (reading 'pluginDirs')
@automattic/vip:bin:dev-environment     at /.../vip/node_modules/lando/lib/config.js:227:32
```
=> Fix loading of empty Lando config

lib/bootstrap.js, package.json, yarn.lock
This fixes the following deprecation:
> npm WARN deprecated uuid@3.0.1: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
=> chore(deps): Update uuid to 9.0.0

lib/cli.js, lib/daemon.js, lib/engine.js, lib/env.js, test/env.spec.js, test/lando.spec.js
* Use the same version detection code for all OSes;
* Do not look specifically for docker-compose-v1;
* Prefer `/usr/bin`
=> refactor: Rewrite version detection logic

plugins/lando-proxy/services/proxy/builder.js
~Ref: https://github.com/Automattic/vip-container-images/pull/368~
Now that we update traefik more often, it is not convenient to update Lando every time there is a new release of traefik. With this PR, we will be using the latest version.
=> feat: Update ghcr.io/automattic/vip-container-images/traefik_openssl to latest

package.json, yarn.lock
Lando does not seem to use `cli-table`; it uses `cli-table3` instead. Time to remove it.
=> chore(deps): Remove cli-table

lib/cache.js, lib/logger.js, lib/utils.js, lib/yaml.js, package.json, plugins/lando-core/index.js, plugins/lando-proxy/app.js, plugins/lando-recipes/lib/options.js, scripts/yaml2json.js, yarn.lock
This PR removes `mkdirp` package. The way Lando uses `mkdirp.sync()` is equivalent to the builtin `fs.mkdirSync()` with `{ recursive: true }` ~and a check for `EEXIST`~ (the check was required for the ancient `mock-fs` package - it has also been updated, so the check is no longer necessary).
Together with #27, this completely removes all versions of `mkdirp`.
Fewer ancient dependencies means fewer vulnerabilities.
Among other things, this slightly improves performance in WSL and virtualized environments: the native implementation does less I/O syscalls.
=> chore(deps): Remove mkdirp

core/art.js, lib/art.js, lib/cli.js, package.json, yarn.lock
This PR removes `sudo-block` and its dependencies:
1. We do allow to run `vip dev-env` as `root` and it is probably too late to check that
2. We have never used `lando.cli.checkPerms()` anyway.
=> chore(deps): Remove sudo-block

lib/config.js, package.json, yarn.lock
Reworked version of https://github.com/Automattic/lando-cli/pull/10
This brings in a lot of bug fixes and improvements :-)
=> chore(deps): Bump dockerode from 2.5.7 to 3.3.5

bin/lando.js, lib/bootstrap.js, lib/config.js, lib/yaml.js, package.json, yarn.lock
This PR updates `js-yaml` to 4.1.0 and fixes the code affected by the [breaking changes](https://github.com/nodeca/js-yaml/blob/master/CHANGELOG.md#400---2021-01-03).
In additional to paying technical debt, this will reduce the number of dependencies for `vip-cli`:
* `vip-cli` uses `js-yaml` 4.1.0;
* The remaining lando plugins reference `js-yaml` 3.x in their dependencies but do not use it, but this can be solved with the `overrides` in `package.json`;
* Switching to the latest `js-yaml` removes the outdated `argparse@1.0.7` (2.0.1 is used by another package as well), `sprintf-js@1.0.3`, and `esprima@4.0.1`.
=> chore(deps): Update js-yaml from 3.4.6 to 4.1.0

.github/workflows/pr-unit-tests.yml
* `macos-10.15` is no longer available
* Node 14 is past EOL
=> ci: Use latest OSes for unit tests

lib/utils.js, test/docker.spec.js
`utils.toLandoContainer()` forcefully uses `_` as a separator in container names. This makes `lando.engine.exists({id: proxyContainer})` in `lando-networking` plugin resolve with `false` when using docker-compose v2, leading to hard-to-reproduce interesting bugs.
=> fix: Compatibility with docker-compose v2

plugins/lando-proxy/app.js
Steps to reproduce:
1. Ensure you are running docker-compose v2
2. Create and start an environment
3. Observe `network lando_proxyedge: network.external.name is deprecated in favor of network.name`
4. Apply the patch and restart the environment
5. The warning should disappear.
=> fix: network.external.name is deprecated in favor of network.name

plugins/lando-proxy/app.js
This PR‌ fixes the issue with `docker-compose` v2.19.x:
```
WARN[0000] a network with name vip-dev-env-proxy_edge exists but was not created for project "viplocal".
Set `external: true` to use an existing network 
network vip-dev-env-proxy_edge was found but has incorrect label com.docker.compose.network set to "edge"
```
Ref: https://github.com/docker/compose/pull/10612/files#diff-1f4d596600c620b3df55dbfbc63e50a6f43b356865fae411c553d0937fbb6d91R1110
=> fix: compatibility with docker-compose v2.19.x

lib/shell.js
Right now, log messages are sometimes very uninformative, and all we have is something like
```
Error at /.../lib/node_modules/@automattic/vip/node_modules/lando/lib/shell.js:158:44 From previous event: at Shell.sh...
```
(more details are in Pendo).
This PR adds more information to the error message so that we at least know wtf is going on.
=> fix: try to make error messages more informative

examples/lando-101/README.md, package.json, yarn.lock
Ref: GHSA-78xj-cgh5-2h22
The only function Lando uses from `ip` is `ip.address()`.
=> security: fix CVE-2023-42282 in ip

.eslintrc.json, lib/app.js, lib/daemon.js, lib/engine.js, lib/env.js, lib/lando.js, lib/plugins.js, lib/shell.js, plugins/lando-core/tasks/info.js, plugins/lando-core/tasks/list.js, plugins/lando-proxy/app.js, plugins/lando-recipes/lib/build.js, plugins/lando-recipes/lib/utils.js, test/cache.spec.js, test/compose.spec.js, test/docker.spec.js
This PR updates ESLint config to support newer JS features.
=> chore: update ecmaScript to 11

lib/env.js
`getOClifHome()` references non-existing `windowsHome()` function. This PR removes that call.
=> fix: remove the call to undefined `windowsHome()`

lib/cli.js, lib/daemon.js
This PR removes the Docker auto-start/stop code. It never worked anyway because we checked for Docker connectivity at the app startup.
This also saves us a call to `docker info`.
=> refactor: remove docker autostart/stop code

.github/workflows/pr-core-tests.yml, .github/workflows/pr-db-tools-tests.yml, .github/workflows/pr-django-tests.yml, .github/workflows/pr-plugins-installed.yml, config.yml, examples/base/README.md, examples/proxy/README.md, examples/scanner/README.md, examples/services/README.md, examples/services/php/Dockerfile, lib/app.js, lib/bootstrap.js, lib/daemon.js, lib/engine.js, lib/factory.js, lib/lando.js, plugins/lando-core/scripts/user-perm-helpers.sh, plugins/lando-events/lib/utils.js, plugins/lando-proxy/index.js, plugins/lando-recipes/lib/build.js
'version' key in Compose was deprecated for a while, but now it also throws an annoying WARN[0000] version is obsolete. 
This PR addresses the issue by removing `version from the ComposeService, which subsequently removes it from each generated compose file.
=> Remove 'version' from ComposeService, drop support for composer v1

lib/env.js
We only check `/usr/local/bin` and `/usr/bin`, by default Homebrew installs packages in `/opt/homebrew`. This PR fixes it.
=> Improve Homebrew compat - check /opt/homebrew/bin for docker and docker-compose

lib/bootstrap.js, lib/compose.js, lib/daemon.js, lib/lando.js, lib/shell.js, test/lando.spec.js
This PR adds support for the `compose` plugin, eliminating the need for the `docker-compose` binary.
=> feat: add support for the `compose` plugin

package.json, plugins/lando-core/index.js, yarn.lock
* get rid of `ip` to fix SSRF (CVE-2024-29415; high severity)
* update `semver` to fix ReDoS (CVE-2022-25883; moderate severity)
* update `tar` to fix DoS (CVE-2024-28863; moderate severity)
=> fix: update vulnerable dependencies

plugins/lando-core/scripts/lando-entrypoint.sh
* if `LANDO_LOAD_KEYS` is not set or `false`, do not run `load-keys.sh`
* misc fixes
=> refactor: Lando entrypoint script

lib/app.js, lib/events.js, lib/plugins.js
In Lando, `Application.init()` walks through the plugin registry (`app.plugins.registry` which is a reference to `lando.plugins.registry`) and invokes `Plugin.load()` on every plugin that has an `app.js` file.
The side effect of the `Plugin.load()` is that it adds every plugin passed to it to the registry. The net effect of this is the growth of the registry: the same plugin may be added several times.
Calls to `Lando.getApp()` and `App.init()` for a different application will double the size of the registry. Because the same plugin will be initialized twice, it will add the same event handlers twice to the application object. This eventually leads to memory leaks and the MaxListenersExceededWarning warning.
See: Automattic/vip-cli#2027
=> fix: exponential growth of plugin registry in `App.init()`

lib/art.js, lib/cli.js, lib/table.js, package.json, yarn.lock
`yargonaut` is no longer maintained and has security issues (see nexdrew/yargonaut#13)
This PR replaces `yargonaut` with `chalk` and `figlet` (direct dependencies of `yargonaut`).
Because we don't need Lando CLI, we can safely eliminate `yargonaut`.
=> chore(deps): replace `yargonaut` with `chalk` and `figlet`

package.json, yarn.lock
This also eliminates `brace-expansion@2.0.1` and thus completely fixes CVE-2025-5889.
Ref: PLTFRM-1041
=> chore(dev-deps): update `mocha` to 11.6.0

lib/logger.js, test/logger.spec.js
While I was working on the logger updates there was a type mismatch, where we tried to use the object for transports { transportName: istanceOfStransport}. However in Winston transports is actually an array. This should fix it
=> Fix a bit of object/array confusion in loggers.

lib/lando.js, lib/plugins.js, test/plugins.spec.js
This PR makes Lando friendly to Jest 30's path resolver.
Tested in Automattic/vip-cli#2421
=> fix: make plugin loader compatible with Jest 30

lib/config.js, lib/lando.js
This PR fixes the `Passing invalid argument types to fs.existsSync is deprecated` warning.
=> fix: DEP0169

lib/scan.js
This pull request makes a small but significant change to the `lib/scan.js` file by increasing the timeout duration for HTTP requests during URL scans. The timeout has been updated from 5000 milliseconds (5 seconds) to 15000 milliseconds (15 seconds) to allow more time for slower requests to complete.
* **Timeout adjustment for URL scans**:
* Increased the default `timeout` value in the function documentation from 5000ms to 15000ms.
* Updated the default `timeout` value in the `scanUrls` function definition to match the new 15000ms value.
=> fix: increase request timeout to 15s

plugins/lando-core/types/utility/Dockerfile
This pull request updates the base image for the utility Dockerfile to use a newer Debian release and improves package installation practices.
Dockerfile base image and installation improvements:
* Updated the base image in `plugins/lando-core/types/utility/Dockerfile` from `debian:buster-slim` to `debian:bookworm-slim` for improved security and up-to-date packages.
* Modified the package installation command to use `--no-install-recommends`, reducing the image size by avoiding unnecessary recommended packages.
=> fix(util): update base image for `devwithlando/util`

.github/workflows/build-util-images.yml
This pull request updates the GitHub Actions workflow for building utility Docker images. The main changes involve switching to using GitHub Container Registry (GHCR) instead of Docker Hub, and renaming the image from `util` to `lando-util`.
**Container image and registry updates:**
* Changed the image name in the build matrix from `util` to `lando-util` to better reflect its purpose.
* Updated the workflow to authenticate with GHCR using GitHub credentials, and changed the image repository from DockerHub to `ghcr.io/automattic/vip-container-images`. The workflow now pushes images to GHCR instead of DockerHub.
* Enabled pushing built images by setting `push: true` (previously `push: false`) in the Docker build step.
=> fix: rename `devwithlando/util` to `ghcr.io/automattic/vip-container-images/lando-util`

plugins/lando-core/types/utility/Dockerfile
This pull request makes a minor update to the `plugins/lando-core/types/utility/Dockerfile` to optimize the Docker image and add a missing dependency.
- Added `openssl` to the list of installed packages to ensure it's available in the utility image.
- Simplified the cleanup command by combining multiple `rm -rf` commands into a single line for efficiency.
=> fix(util): add `openssl` package
